2024-09-21 21:45:31,847 [ERROR] Ошибка при запуске бота: no such table: promo_codes
2024-09-21 21:45:38,765 [ERROR] Ошибка при запуске бота: no such table: promo_codes
2024-09-21 21:47:34,395 [ERROR] Ошибка при запуске бота: no such table: promo_codes
2024-09-21 21:48:31,308 [ERROR] Ошибка при запуске бота: no such table: promo_codes
2024-09-21 22:05:55,185 [ERROR] Ошибка при запуске бота: no such table: promo_codes
2024-09-21 22:06:08,609 [ERROR] Ошибка при запуске бота: no such table: promo_codes
2024-09-21 22:08:00,663 [ERROR] Ошибка при запуске бота: no such table: promo_codes
2024-09-21 22:09:11,263 [ERROR] Ошибка при запуске бота: table promo_codes already exists
2024-09-21 22:09:51,455 [ERROR] Ошибка при запуске бота: no such table: promo_codes
2024-09-21 22:17:11,500 [INFO] Инициализация базы данных начата.
2024-09-21 22:17:11,503 [INFO] Таблица users успешно создана или уже существует.
2024-09-21 22:17:11,504 [INFO] Таблица cars успешно создана или уже существует.
2024-09-21 22:17:11,504 [INFO] Таблица purchases успешно создана или уже существует.
2024-09-21 22:17:11,505 [INFO] Таблица earnings успешно создана или уже существует.
2024-09-21 22:17:11,505 [INFO] Таблица promo_codes успешно создана или уже существует.
2024-09-21 22:17:11,506 [INFO] Таблица channels успешно создана или уже существует.
2024-09-21 22:17:11,509 [ERROR] Ошибка при запуске бота: no such table: promo_codes
2024-09-21 22:21:28,285 [INFO] Инициализация базы данных начата.
2024-09-21 22:21:28,287 [INFO] Таблица users успешно создана или уже существует.
2024-09-21 22:21:28,287 [INFO] Таблица cars успешно создана или уже существует.
2024-09-21 22:21:28,288 [INFO] Таблица purchases успешно создана или уже существует.
2024-09-21 22:21:28,288 [INFO] Таблица earnings успешно создана или уже существует.
2024-09-21 22:21:28,288 [INFO] Таблица channels успешно создана или уже существует.
2024-09-21 22:21:28,289 [INFO] Таблица VALUES успешно создана или уже существует.
2024-09-21 22:21:28,291 [ERROR] Ошибка при запуске бота: no such table: promo_codes
2024-09-21 22:22:09,651 [INFO] Инициализация базы данных начата.
2024-09-21 22:22:09,654 [INFO] Таблица users успешно создана или уже существует.
2024-09-21 22:22:09,655 [INFO] Таблица cars успешно создана или уже существует.
2024-09-21 22:22:09,655 [INFO] Таблица purchases успешно создана или уже существует.
2024-09-21 22:22:09,655 [INFO] Таблица earnings успешно создана или уже существует.
2024-09-21 22:22:09,656 [INFO] Таблица channels успешно создана или уже существует.
2024-09-21 22:22:09,656 [INFO] Таблица VALUES успешно создана или уже существует.
2024-09-21 22:22:09,657 [INFO] Таблица promo_codes успешно создана или уже существует.
2024-09-21 22:22:09,659 [ERROR] Ошибка при запуске бота: no such table: promo_codes
2024-09-21 23:01:34,518 [INFO] Инициализация базы данных начата.
2024-09-21 23:01:34,525 [INFO] Таблица users успешно создана или уже существует.
2024-09-21 23:01:34,526 [INFO] Таблица cars успешно создана или уже существует.
2024-09-21 23:01:34,527 [INFO] Таблица purchases успешно создана или уже существует.
2024-09-21 23:01:34,528 [INFO] Таблица earnings успешно создана или уже существует.
2024-09-21 23:01:34,529 [INFO] Таблица channels успешно создана или уже существует.
2024-09-21 23:01:34,529 [INFO] Таблица VALUES успешно создана или уже существует.
2024-09-21 23:01:34,530 [INFO] Таблица promo_codes успешно создана или уже существует.
2024-09-21 23:01:34,534 [ERROR] Ошибка при запуске бота: no such table: promo_codes
2024-09-21 23:01:34,535 [INFO] Инициализация базы данных начата.
2024-09-21 23:01:34,538 [INFO] Таблица users успешно создана или уже существует.
2024-09-21 23:01:34,538 [INFO] Таблица cars успешно создана или уже существует.
2024-09-21 23:01:34,538 [INFO] Таблица purchases успешно создана или уже существует.
2024-09-21 23:01:34,539 [INFO] Таблица earnings успешно создана или уже существует.
2024-09-21 23:01:34,539 [INFO] Таблица channels успешно создана или уже существует.
2024-09-21 23:01:34,539 [INFO] Таблица VALUES успешно создана или уже существует.
2024-09-21 23:01:34,540 [INFO] Таблица promo_codes успешно создана или уже существует.
2024-09-21 23:01:34,546 [ERROR] Ошибка при запуске бота: no such table: promo_codes
2024-09-21 23:01:48,650 [INFO] Инициализация базы данных начата.
2024-09-21 23:01:48,654 [INFO] Таблица users успешно создана или уже существует.
2024-09-21 23:01:48,654 [INFO] Таблица cars успешно создана или уже существует.
2024-09-21 23:01:48,654 [INFO] Таблица purchases успешно создана или уже существует.
2024-09-21 23:01:48,655 [INFO] Таблица earnings успешно создана или уже существует.
2024-09-21 23:01:48,655 [INFO] Таблица channels успешно создана или уже существует.
2024-09-21 23:01:48,656 [INFO] Таблица VALUES успешно создана или уже существует.
2024-09-21 23:01:48,656 [INFO] Таблица promo_codes успешно создана или уже существует.
2024-09-21 23:01:48,662 [ERROR] Ошибка при запуске бота: no such table: promo_codes
2024-09-21 23:01:48,664 [INFO] Инициализация базы данных начата.
2024-09-21 23:01:48,667 [INFO] Таблица users успешно создана или уже существует.
2024-09-21 23:01:48,667 [INFO] Таблица cars успешно создана или уже существует.
2024-09-21 23:01:48,667 [INFO] Таблица purchases успешно создана или уже существует.
2024-09-21 23:01:48,667 [INFO] Таблица earnings успешно создана или уже существует.
2024-09-21 23:01:48,668 [INFO] Таблица channels успешно создана или уже существует.
2024-09-21 23:01:48,668 [INFO] Таблица VALUES успешно создана или уже существует.
2024-09-21 23:01:48,668 [INFO] Таблица promo_codes успешно создана или уже существует.
2024-09-21 23:01:48,672 [ERROR] Ошибка при запуске бота: no such table: promo_codes
2024-09-21 23:02:05,982 [INFO] Инициализация базы данных начата.
2024-09-21 23:02:05,986 [INFO] Таблица users успешно создана или уже существует.
2024-09-21 23:02:05,987 [INFO] Таблица cars успешно создана или уже существует.
2024-09-21 23:02:05,987 [INFO] Таблица purchases успешно создана или уже существует.
2024-09-21 23:02:05,988 [INFO] Таблица earnings успешно создана или уже существует.
2024-09-21 23:02:05,988 [INFO] Таблица channels успешно создана или уже существует.
2024-09-21 23:02:05,989 [INFO] Таблица VALUES успешно создана или уже существует.
2024-09-21 23:02:05,990 [INFO] Таблица promo_codes успешно создана или уже существует.
2024-09-21 23:02:05,995 [ERROR] Ошибка при запуске бота: no such table: promo_codes
2024-09-21 23:12:48,829 [INFO] Инициализация базы данных начата.
2024-09-21 23:12:48,831 [INFO] Таблица users успешно создана или уже существует.
2024-09-21 23:12:48,832 [INFO] Таблица cars успешно создана или уже существует.
2024-09-21 23:12:48,832 [INFO] Таблица purchases успешно создана или уже существует.
2024-09-21 23:12:48,832 [INFO] Таблица earnings успешно создана или уже существует.
2024-09-21 23:12:48,833 [INFO] Таблица channels успешно создана или уже существует.
2024-09-21 23:12:48,833 [INFO] Данные в таблице channels вставлены успешно.
2024-09-21 23:12:48,833 [INFO] Таблица promo_codes успешно создана или уже существует.
2024-09-21 23:12:48,839 [ERROR] Ошибка при запуске бота: no such table: promo_codes
2024-09-21 23:14:29,165 [INFO] Инициализация базы данных начата.
2024-09-21 23:14:29,168 [INFO] Таблица users успешно создана или уже существует.
2024-09-21 23:14:29,168 [INFO] Таблица cars успешно создана или уже существует.
2024-09-21 23:14:29,169 [INFO] Таблица purchases успешно создана или уже существует.
2024-09-21 23:14:29,169 [INFO] Таблица earnings успешно создана или уже существует.
2024-09-21 23:14:29,169 [INFO] Таблица channels успешно создана или уже существует.
2024-09-21 23:14:29,170 [INFO] Данные в таблице channels вставлены успешно.
2024-09-21 23:14:29,170 [INFO] Таблица promo_codes успешно создана или уже существует.
2024-09-21 23:14:29,175 [ERROR] Ошибка при запуске бота: no such table: promo_codes
2024-09-21 23:17:28,187 [INFO] Инициализация базы данных начата.
2024-09-21 23:17:28,189 [INFO] Таблица users успешно создана или уже существует.
2024-09-21 23:17:28,190 [INFO] Таблица cars успешно создана или уже существует.
2024-09-21 23:17:28,190 [INFO] Таблица purchases успешно создана или уже существует.
2024-09-21 23:17:28,190 [INFO] Таблица earnings успешно создана или уже существует.
2024-09-21 23:17:28,190 [INFO] Таблица channels успешно создана или уже существует.
2024-09-21 23:17:28,192 [INFO] Данные в таблице channels вставлены успешно.
2024-09-21 23:17:28,192 [INFO] Таблица promo_codes успешно создана или уже существует.
2024-09-21 23:17:28,197 [ERROR] Ошибка при запуске бота: no such table: promo_codes
2024-09-21 23:25:26,862 [INFO] Инициализация базы данных начата.
2024-09-21 23:25:26,864 [INFO] Таблица users успешно создана или уже существует.
2024-09-21 23:25:26,866 [INFO] Таблица cars успешно создана или уже существует.
2024-09-21 23:25:26,866 [INFO] Таблица purchases успешно создана или уже существует.
2024-09-21 23:25:26,867 [INFO] Таблица earnings успешно создана или уже существует.
2024-09-21 23:25:26,867 [INFO] Таблица channels успешно создана или уже существует.
2024-09-21 23:25:26,867 [INFO] Данные в таблице channels вставлены успешно.
2024-09-21 23:25:26,867 [INFO] Таблица promo_codes успешно создана или уже существует.
2024-09-21 23:25:26,872 [ERROR] Ошибка при запуске бота: no such table: promo_codes
2024-09-21 23:25:43,266 [INFO] Инициализация базы данных начата.
2024-09-21 23:25:43,269 [INFO] Таблица users успешно создана или уже существует.
2024-09-21 23:25:43,270 [INFO] Таблица cars успешно создана или уже существует.
2024-09-21 23:25:43,270 [INFO] Таблица purchases успешно создана или уже существует.
2024-09-21 23:25:43,270 [INFO] Таблица earnings успешно создана или уже существует.
2024-09-21 23:25:43,270 [INFO] Таблица channels успешно создана или уже существует.
2024-09-21 23:25:43,271 [INFO] Данные в таблице channels вставлены успешно.
2024-09-21 23:25:43,275 [ERROR] Ошибка при запуске бота: no such table: promo_codes
2024-09-21 23:32:25,163 [INFO] Инициализация базы данных начата.
2024-09-21 23:32:25,166 [INFO] Таблица promo_codes успешно создана или уже существует.
2024-09-21 23:32:25,168 [ERROR] Ошибка при запуске бота: no such table: promo_codes
2024-09-21 23:51:59,239 [INFO] Инициализация базы данных начата.
2024-09-21 23:51:59,247 [INFO] Таблица promo_codes успешно создана или уже существует.
2024-09-21 23:51:59,250 [ERROR] Ошибка при запуске бота: no such table: promo_codes
2024-09-22 00:01:01,358 [INFO] Инициализация базы данных начата.
2024-09-22 00:01:01,363 [ERROR] Ошибка при запуске бота: no such table: promo_codes
2024-09-22 00:01:19,953 [INFO] Инициализация базы данных начата.
2024-09-22 00:01:19,958 [ERROR] Ошибка при запуске бота: no such table: promo_codes
2024-09-22 00:01:44,306 [INFO] Инициализация базы данных начата.
2024-09-22 00:01:44,310 [ERROR] Ошибка при запуске бота: no such table: promo_codes
2024-09-22 00:02:16,073 [INFO] Инициализация базы данных начата.
2024-09-22 00:02:16,078 [ERROR] Ошибка при запуске бота: no such table: promo_codes
2024-09-22 00:07:05,645 [INFO] Инициализация базы данных начата.
2024-09-22 00:07:05,653 [ERROR] Ошибка при запуске бота: no such table: promo_codes
2024-09-22 00:10:00,318 [INFO] Инициализация базы данных начата.
2024-09-22 00:10:00,327 [ERROR] Ошибка при запуске бота: no such table: promo_codes
2024-09-22 00:11:51,823 [INFO] Инициализация базы данных начата.
2024-09-22 00:11:51,829 [ERROR] Ошибка при запуске бота: no such table: promo_codes
2024-09-22 00:12:52,787 [INFO] Инициализация базы данных начата.
2024-09-22 00:12:52,791 [ERROR] Ошибка при создании таблицы users: Cannot operate on a closed cursor.
2024-09-22 00:12:52,791 [INFO] Данные в таблице users вставлены успешно.
2024-09-22 00:12:52,794 [ERROR] Ошибка при запуске бота: no such table: promo_codes
2024-09-22 00:13:43,730 [INFO] Инициализация базы данных начата.
2024-09-22 00:13:43,736 [ERROR] Ошибка при запуске бота: no such table: promo_codes
2024-09-22 00:18:09,048 [INFO] Инициализация базы данных начата.
2024-09-22 00:18:09,055 [INFO] Таблица promo_codes успешно создана или уже существует.
2024-09-22 00:18:09,057 [ERROR] Ошибка при запуске бота: no such table: promo_codes
2024-09-22 00:19:18,581 [INFO] Инициализация базы данных начата.
2024-09-22 00:19:18,587 [INFO] Таблица promo_codes успешно создана или уже существует.
2024-09-22 00:19:18,589 [ERROR] Ошибка при запуске бота: no such table: promo_codes
2024-09-22 00:21:52,544 [INFO] Инициализация базы данных начата.
2024-09-22 00:21:52,546 [INFO] Таблица promo_codes успешно создана или уже существует.
2024-09-22 00:21:52,549 [ERROR] Ошибка при запуске бота: no such table: promo_codes
2024-09-22 00:21:52,549 [INFO] Инициализация базы данных начата.
2024-09-22 00:21:52,551 [INFO] Таблица promo_codes успешно создана или уже существует.
2024-09-22 00:28:21,115 [INFO] Инициализация базы данных начата.
2024-09-22 00:28:21,119 [INFO] Таблица users создаеться
2024-09-22 00:28:21,119 [INFO] Таблица users успешно создана или уже существует.
2024-09-22 00:28:21,120 [INFO] Таблица cars успешно создана или уже существует.
2024-09-22 00:28:21,120 [INFO] Таблица purchases успешно создана или уже существует.
2024-09-22 00:28:21,121 [INFO] Таблица earnings успешно создана или уже существует.
2024-09-22 00:28:21,121 [INFO] Таблица channels успешно создана или уже существует.
2024-09-22 00:28:21,122 [INFO] Данные в таблицу channels успешно добавлены.
2024-09-22 00:28:21,122 [INFO] Таблица promo_codes успешно создана или уже существует.
2024-09-22 00:28:21,130 [ERROR] Ошибка при запуске бота: no such table: promo_codes
2024-09-22 00:28:40,364 [INFO] Инициализация базы данных начата.
2024-09-22 00:28:40,367 [INFO] Таблица users создаеться
2024-09-22 00:28:40,368 [INFO] Таблица users успешно создана или уже существует. /n
2024-09-22 00:28:40,368 [INFO] Таблица cars успешно создана или уже существует.
2024-09-22 00:28:40,369 [INFO] Таблица purchases успешно создана или уже существует.
2024-09-22 00:28:40,369 [INFO] Таблица earnings успешно создана или уже существует.
2024-09-22 00:28:40,369 [INFO] Таблица channels успешно создана или уже существует.
2024-09-22 00:28:40,370 [INFO] Данные в таблицу channels успешно добавлены.
2024-09-22 00:28:40,371 [INFO] Таблица promo_codes успешно создана или уже существует.
2024-09-22 00:28:40,378 [ERROR] Ошибка при запуске бота: no such table: promo_codes
2024-09-22 00:38:40,902 [INFO] Инициализация базы данных начата.
2024-09-22 00:38:40,904 [INFO] Таблица users создаеться
2024-09-22 00:38:40,905 [INFO] Таблица users успешно создана или уже существует.
2024-09-22 00:38:40,905 [INFO]  
2024-09-22 00:38:40,905 [INFO] Таблица cars создаеться
2024-09-22 00:38:40,905 [INFO] Таблица cars успешно создана или уже существует.
2024-09-22 00:38:40,905 [INFO]  
2024-09-22 00:38:40,907 [INFO] Таблица purchases создаеться
2024-09-22 00:38:40,907 [INFO] Таблица purchases успешно создана или уже существует.
2024-09-22 00:38:40,907 [INFO]  
2024-09-22 00:38:40,907 [INFO] Таблица earnings создаеться
2024-09-22 00:38:40,908 [INFO] Таблица earnings успешно создана или уже существует.
2024-09-22 00:38:40,908 [INFO]  
2024-09-22 00:38:40,908 [INFO] Таблица channels создаеться
2024-09-22 00:38:40,909 [INFO] Таблица channels успешно создана или уже существует.
2024-09-22 00:38:40,909 [INFO]  
2024-09-22 00:38:40,909 [INFO] Таблица VALUES создана
2024-09-22 00:38:40,909 [INFO] Данные в таблицу channels успешно добавлены.
2024-09-22 00:38:40,910 [INFO]  
2024-09-22 00:38:40,910 [INFO] Таблица promo_codes создаеться
2024-09-22 00:38:40,910 [INFO] Таблица promo_codes успешно создана или уже существует.
2024-09-22 00:38:40,916 [ERROR] Ошибка при запуске бота: no such table: promo_codes
2024-09-22 00:49:56,858 [INFO] Инициализация базы данных начата.
2024-09-22 00:49:56,865 [INFO] Таблица users создаеться
2024-09-22 00:49:56,865 [ERROR] Ошибка при инициализации базы данных: Cannot operate on a closed cursor.
2024-09-22 00:49:56,869 [ERROR] Ошибка при запуске бота: no such table: promo_codes
2024-09-22 00:52:24,007 [INFO] Инициализация базы данных начата.
2024-09-22 00:52:24,010 [INFO] Таблица users создается
2024-09-22 00:52:24,012 [INFO] Таблица users успешно создана или уже существует.
2024-09-22 00:52:24,012 [INFO] Таблица cars создается
2024-09-22 00:52:24,013 [INFO] Таблица cars успешно создана или уже существует.
2024-09-22 00:52:24,013 [INFO] Таблица purchases создается
2024-09-22 00:52:24,013 [INFO] Таблица purchases успешно создана или уже существует.
2024-09-22 00:52:24,014 [INFO] Таблица earnings создается
2024-09-22 00:52:24,014 [INFO] Таблица earnings успешно создана или уже существует.
2024-09-22 00:52:24,014 [INFO] Таблица channels создается
2024-09-22 00:52:24,014 [INFO] Таблица channels успешно создана или уже существует.
2024-09-22 00:52:24,014 [INFO] Добавление данных в таблицу channels
2024-09-22 00:52:24,015 [INFO] Данные в таблицу channels успешно добавлены.
2024-09-22 00:52:24,015 [INFO] Таблица promo_codes создается
2024-09-22 00:52:24,015 [INFO] Таблица promo_codes успешно создана или уже существует.
2024-09-22 00:52:24,021 [INFO] Инициализация базы данных завершена.
2024-09-22 00:52:24,025 [ERROR] Ошибка при запуске бота: no such table: promo_codes
2024-09-22 01:21:17,849 [INFO] Инициализация базы данных начата.
2024-09-22 01:21:17,851 [INFO] Таблица users создается
2024-09-22 01:21:17,852 [INFO] Таблица users успешно создана или уже существует.
2024-09-22 01:21:17,852 [INFO] Таблица cars создается
2024-09-22 01:21:17,853 [INFO] Таблица cars успешно создана или уже существует.
2024-09-22 01:21:17,853 [INFO] Таблица purchases создается
2024-09-22 01:21:17,853 [INFO] Таблица purchases успешно создана или уже существует.
2024-09-22 01:21:17,854 [INFO] Таблица earnings создается
2024-09-22 01:21:17,854 [INFO] Таблица earnings успешно создана или уже существует.
2024-09-22 01:21:17,854 [INFO] Таблица channels создается
2024-09-22 01:21:17,855 [INFO] Таблица channels успешно создана или уже существует.
2024-09-22 01:21:17,855 [INFO] Добавление данных в таблицу channels
2024-09-22 01:21:17,855 [INFO] Данные в таблицу channels успешно добавлены.
2024-09-22 01:21:17,856 [INFO] Таблица promo_codes создается
2024-09-22 01:21:17,856 [INFO] Таблица promo_codes успешно создана или уже существует.
2024-09-22 01:21:17,861 [INFO] Инициализация базы данных завершена.
2024-09-22 01:21:17,863 [INFO] Вставка заранее подготовленных промокодов в базу данных
2024-09-22 01:21:17,865 [ERROR] Ошибка при запуске бота: no such table: promo_codes
2024-09-22 01:22:52,065 [INFO] Инициализация базы данных начата.
2024-09-22 01:22:52,069 [INFO] Таблица users создается
2024-09-22 01:22:52,073 [INFO] Таблица users успешно создана или уже существует.
2024-09-22 01:22:52,073 [INFO] Таблица cars создается
2024-09-22 01:22:52,075 [INFO] Таблица cars успешно создана или уже существует.
2024-09-22 01:22:52,075 [INFO] Таблица purchases создается
2024-09-22 01:22:52,077 [INFO] Таблица purchases успешно создана или уже существует.
2024-09-22 01:22:52,077 [INFO] Таблица earnings создается
2024-09-22 01:22:52,078 [INFO] Таблица earnings успешно создана или уже существует.
2024-09-22 01:22:52,078 [INFO] Таблица channels создается
2024-09-22 01:22:52,079 [INFO] Таблица channels успешно создана или уже существует.
2024-09-22 01:22:52,079 [INFO] Добавление данных в таблицу channels
2024-09-22 01:22:52,079 [INFO] Данные в таблицу channels успешно добавлены.
2024-09-22 01:22:52,079 [INFO] Таблица promo_codes создается
2024-09-22 01:22:52,080 [INFO] Таблица promo_codes успешно создана или уже существует.
2024-09-22 01:22:52,083 [INFO] Инициализация базы данных завершена.
2024-09-22 01:22:52,085 [INFO] Вставка заранее подготовленных промокодов в базу данных
2024-09-22 01:22:52,086 [ERROR] Ошибка при запуске бота: no such table: promo_codes
2024-09-22 01:36:41,527 [INFO] Инициализация базы данных начата.
2024-09-22 01:36:41,529 [INFO] Таблица users создается
2024-09-22 01:36:41,530 [INFO] Таблица users успешно создана или уже существует.
2024-09-22 01:36:41,530 [INFO] Таблица cars создается
2024-09-22 01:36:41,530 [INFO] Таблица cars успешно создана или уже существует.
2024-09-22 01:36:41,532 [INFO] Таблица purchases создается
2024-09-22 01:36:41,532 [INFO] Таблица purchases успешно создана или уже существует.
2024-09-22 01:36:41,532 [INFO] Таблица earnings создается
2024-09-22 01:36:41,533 [INFO] Таблица earnings успешно создана или уже существует.
2024-09-22 01:36:41,534 [INFO] Таблица channels создается
2024-09-22 01:36:41,534 [INFO] Таблица channels успешно создана или уже существует.
2024-09-22 01:36:41,534 [INFO] Добавление данных в таблицу channels
2024-09-22 01:36:41,535 [INFO] Данные в таблицу channels успешно добавлены.
2024-09-22 01:36:41,535 [INFO] Таблица promo_codes создается
2024-09-22 01:36:41,535 [INFO] Таблица promo_codes успешно создана или уже существует.
2024-09-22 01:36:41,541 [INFO] Инициализация базы данных завершена.
2024-09-22 01:36:41,543 [INFO] Таблицы в базе данных: [('users',), ('cars',), ('purchases',), ('earnings',), ('sqlite_sequence',), ('channels',), ('promo_codes',)]
2024-09-22 01:36:41,545 [INFO] Вставка заранее подготовленных промокодов в базу данных
2024-09-22 01:36:41,546 [INFO] Добавляем промокод: CODE1, категория: normal, награда: 10
2024-09-22 01:36:41,546 [INFO] Добавляем промокод: CODE2, категория: normal, награда: 10
2024-09-22 01:36:41,546 [INFO] Добавляем промокод: CODE3, категория: normal, награда: 10
2024-09-22 01:36:41,546 [INFO] Добавляем промокод: CODE4, категория: normal, награда: 30
2024-09-22 01:36:41,547 [INFO] Добавляем промокод: CODE5, категория: normal, награда: 30
2024-09-22 01:36:41,548 [INFO] Добавляем промокод: CODE6, категория: normal, награда: 50
2024-09-22 01:36:41,548 [INFO] Добавляем промокод: SPECIAL1, категория: special, награда: 100
2024-09-22 01:36:41,549 [INFO] Добавляем промокод: SPECIAL2, категория: special, награда: 150
2024-09-22 01:36:41,549 [INFO] Добавляем промокод: SPECIAL3, категория: special, награда: 200
2024-09-22 01:36:41,550 [INFO] Добавляем промокод: ADVANCED1, категория: advanced, награда: 350
2024-09-22 01:36:41,550 [INFO] Добавляем промокод: ADVANCED2, категория: advanced, награда: 400
2024-09-22 01:36:41,550 [INFO] Добавляем промокод: ADVANCED3, категория: advanced, награда: 450
2024-09-22 01:36:41,552 [INFO] Промокоды успешно вставлены в базу данных
2024-09-22 01:36:41,554 [INFO] Бот успешно запущен.
2024-09-22 01:44:17,022 [INFO] Инициализация базы данных начата.
2024-09-22 01:44:17,026 [INFO] Таблица users создается
2024-09-22 01:44:17,027 [INFO] Таблица users успешно создана или уже существует.
2024-09-22 01:44:17,028 [INFO] Таблица cars создается
2024-09-22 01:44:17,028 [INFO] Таблица cars успешно создана или уже существует.
2024-09-22 01:44:17,029 [INFO] Таблица purchases создается
2024-09-22 01:44:17,029 [INFO] Таблица purchases успешно создана или уже существует.
2024-09-22 01:44:17,030 [INFO] Таблица earnings создается
2024-09-22 01:44:17,030 [INFO] Таблица earnings успешно создана или уже существует.
2024-09-22 01:44:17,030 [INFO] Таблица channels создается
2024-09-22 01:44:17,031 [INFO] Таблица channels успешно создана или уже существует.
2024-09-22 01:44:17,031 [INFO] Добавление данных в таблицу channels
2024-09-22 01:44:17,031 [INFO] Данные в таблицу channels успешно добавлены.
2024-09-22 01:44:17,031 [INFO] Таблица promo_codes создается
2024-09-22 01:44:17,032 [INFO] Таблица promo_codes успешно создана или уже существует.
2024-09-22 01:44:17,036 [INFO] Инициализация базы данных завершена.
2024-09-22 01:44:17,039 [INFO] Таблицы в базе данных: [('users',), ('cars',), ('purchases',), ('earnings',), ('sqlite_sequence',), ('channels',), ('promo_codes',)]
2024-09-22 01:44:17,041 [INFO] Вставка заранее подготовленных промокодов в базу данных
2024-09-22 01:44:17,043 [INFO] Добавляем промокод: CODE1, категория: normal, награда: 10
2024-09-22 01:44:17,043 [INFO] Добавляем промокод: CODE2, категория: normal, награда: 10
2024-09-22 01:44:17,043 [INFO] Добавляем промокод: CODE3, категория: normal, награда: 10
2024-09-22 01:44:17,044 [INFO] Добавляем промокод: CODE4, категория: normal, награда: 30
2024-09-22 01:44:17,044 [INFO] Добавляем промокод: CODE5, категория: normal, награда: 30
2024-09-22 01:44:17,045 [INFO] Добавляем промокод: CODE6, категория: normal, награда: 50
2024-09-22 01:44:17,045 [INFO] Добавляем промокод: SPECIAL1, категория: special, награда: 100
2024-09-22 01:44:17,045 [INFO] Добавляем промокод: SPECIAL2, категория: special, награда: 150
2024-09-22 01:44:17,046 [INFO] Добавляем промокод: SPECIAL3, категория: special, награда: 200
2024-09-22 01:44:17,046 [INFO] Добавляем промокод: ADVANCED1, категория: advanced, награда: 350
2024-09-22 01:44:17,046 [INFO] Добавляем промокод: ADVANCED2, категория: advanced, награда: 400
2024-09-22 01:44:17,047 [INFO] Добавляем промокод: ADVANCED3, категория: advanced, награда: 450
2024-09-22 01:44:17,048 [INFO] Промокоды успешно вставлены в базу данных
2024-09-22 01:44:17,050 [INFO] Бот успешно запущен.
2024-09-22 01:51:06,765 [INFO] Инициализация базы данных начата.
2024-09-22 01:51:06,768 [INFO] Таблица users создается
2024-09-22 01:51:06,768 [INFO] Таблица users успешно создана или уже существует.
2024-09-22 01:51:06,768 [INFO] Таблица cars создается
2024-09-22 01:51:06,769 [INFO] Таблица cars успешно создана или уже существует.
2024-09-22 01:51:06,769 [INFO] Таблица purchases создается
2024-09-22 01:51:06,769 [INFO] Таблица purchases успешно создана или уже существует.
2024-09-22 01:51:06,769 [INFO] Таблица earnings создается
2024-09-22 01:51:06,770 [INFO] Таблица earnings успешно создана или уже существует.
2024-09-22 01:51:06,770 [INFO] Таблица channels создается
2024-09-22 01:51:06,770 [INFO] Таблица channels успешно создана или уже существует.
2024-09-22 01:51:06,770 [INFO] Добавление данных в таблицу channels
2024-09-22 01:51:06,771 [INFO] Данные в таблицу channels успешно добавлены.
2024-09-22 01:51:06,771 [INFO] Таблица promo_codes создается
2024-09-22 01:51:06,771 [INFO] Таблица promo_codes успешно создана или уже существует.
2024-09-22 01:51:06,776 [INFO] Инициализация базы данных завершена.
2024-09-22 01:51:06,778 [INFO] Таблицы в базе данных: [('users',), ('cars',), ('purchases',), ('earnings',), ('sqlite_sequence',), ('channels',), ('promo_codes',)]
2024-09-22 01:51:06,780 [INFO] Вставка заранее подготовленных промокодов в базу данных
2024-09-22 01:51:06,781 [INFO] Добавляем промокод: CODE1, категория: normal, награда: 10
2024-09-22 01:51:06,781 [INFO] Добавляем промокод: CODE2, категория: normal, награда: 10
2024-09-22 01:51:06,782 [INFO] Добавляем промокод: CODE3, категория: normal, награда: 10
2024-09-22 01:51:06,782 [INFO] Добавляем промокод: CODE4, категория: normal, награда: 30
2024-09-22 01:51:06,782 [INFO] Добавляем промокод: CODE5, категория: normal, награда: 30
2024-09-22 01:51:06,784 [INFO] Добавляем промокод: CODE6, категория: normal, награда: 50
2024-09-22 01:51:06,784 [INFO] Добавляем промокод: SPECIAL1, категория: special, награда: 100
2024-09-22 01:51:06,784 [INFO] Добавляем промокод: SPECIAL2, категория: special, награда: 150
2024-09-22 01:51:06,785 [INFO] Добавляем промокод: SPECIAL3, категория: special, награда: 200
2024-09-22 01:51:06,785 [INFO] Добавляем промокод: ADVANCED1, категория: advanced, награда: 350
2024-09-22 01:51:06,785 [INFO] Добавляем промокод: ADVANCED2, категория: advanced, награда: 400
2024-09-22 01:51:06,785 [INFO] Добавляем промокод: ADVANCED3, категория: advanced, награда: 450
2024-09-22 01:51:06,789 [INFO] Промокоды успешно вставлены в базу данных
2024-09-22 01:51:06,790 [INFO] Бот успешно запущен.
2024-09-22 01:57:35,470 [INFO] Инициализация базы данных начата.
2024-09-22 01:57:35,473 [INFO] Таблица users создается
2024-09-22 01:57:35,474 [INFO] Таблица users успешно создана или уже существует.
2024-09-22 01:57:35,474 [INFO] Таблица cars создается
2024-09-22 01:57:35,475 [INFO] Таблица cars успешно создана или уже существует.
2024-09-22 01:57:35,475 [INFO] Таблица purchases создается
2024-09-22 01:57:35,475 [INFO] Таблица purchases успешно создана или уже существует.
2024-09-22 01:57:35,475 [INFO] Таблица earnings создается
2024-09-22 01:57:35,475 [INFO] Таблица earnings успешно создана или уже существует.
2024-09-22 01:57:35,476 [INFO] Таблица channels создается
2024-09-22 01:57:35,476 [INFO] Таблица channels успешно создана или уже существует.
2024-09-22 01:57:35,476 [INFO] Добавление данных в таблицу channels
2024-09-22 01:57:35,476 [INFO] Данные в таблицу channels успешно добавлены.
2024-09-22 01:57:35,477 [INFO] Таблица promo_codes создается
2024-09-22 01:57:35,477 [INFO] Таблица promo_codes успешно создана или уже существует.
2024-09-22 01:57:35,481 [INFO] Инициализация базы данных завершена.
2024-09-22 01:57:35,485 [INFO] Таблицы в базе данных: [('users',), ('cars',), ('purchases',), ('earnings',), ('sqlite_sequence',), ('channels',), ('promo_codes',)]
2024-09-22 01:57:35,487 [INFO] Вставка заранее подготовленных промокодов в базу данных
2024-09-22 01:57:35,489 [INFO] Добавляем промокод: CODE1, категория: normal, награда: 10
2024-09-22 01:57:35,489 [INFO] Добавляем промокод: CODE2, категория: normal, награда: 10
2024-09-22 01:57:35,490 [INFO] Добавляем промокод: CODE3, категория: normal, награда: 10
2024-09-22 01:57:35,491 [INFO] Добавляем промокод: CODE4, категория: normal, награда: 30
2024-09-22 01:57:35,491 [INFO] Добавляем промокод: CODE5, категория: normal, награда: 30
2024-09-22 01:57:35,491 [INFO] Добавляем промокод: CODE6, категория: normal, награда: 50
2024-09-22 01:57:35,492 [INFO] Добавляем промокод: SPECIAL1, категория: special, награда: 100
2024-09-22 01:57:35,492 [INFO] Добавляем промокод: SPECIAL2, категория: special, награда: 150
2024-09-22 01:57:35,493 [INFO] Добавляем промокод: SPECIAL3, категория: special, награда: 200
2024-09-22 01:57:35,493 [INFO] Добавляем промокод: ADVANCED1, категория: advanced, награда: 350
2024-09-22 01:57:35,493 [INFO] Добавляем промокод: ADVANCED2, категория: advanced, награда: 400
2024-09-22 01:57:35,494 [INFO] Добавляем промокод: ADVANCED3, категория: advanced, награда: 450
2024-09-22 01:57:35,495 [INFO] Промокоды успешно вставлены в базу данных
2024-09-22 01:57:35,497 [INFO] Бот успешно запущен.
2024-09-22 01:57:35,497 [INFO] Start polling.
2024-09-22 01:57:46,960 [WARNING] Пользователь с ID 5598142592 не найден.
2024-09-22 01:57:47,371 [ERROR] Ошибка при проверке подписки для пользователя 5598142592: Member list is inaccessible
2024-09-22 01:57:47,374 [ERROR] Ошибка при проверке подписки для пользователя 5598142592: Member list is inaccessible
2024-09-22 01:57:47,375 [ERROR] Ошибка при проверке подписки для пользователя 5598142592: Member list is inaccessible
2024-09-22 01:57:47,376 [ERROR] Ошибка при проверке подписки для пользователя 5598142592: Member list is inaccessible
2024-09-22 01:57:47,377 [ERROR] Ошибка при проверке подписки для пользователя 5598142592: Member list is inaccessible
2024-09-22 01:57:47,396 [ERROR] Ошибка при проверке подписки для пользователя 5598142592: Member list is inaccessible
2024-09-22 01:57:47,426 [ERROR] Ошибка при проверке подписки для пользователя 5598142592: Member list is inaccessible
2024-09-22 01:57:47,448 [ERROR] Ошибка при проверке подписки для пользователя 5598142592: Member list is inaccessible
2024-09-22 01:58:33,525 [ERROR] Ошибка при проверке подписки для пользователя 5598142592: Member list is inaccessible
2024-09-22 02:01:31,574 [ERROR] Ошибка при проверке подписки для пользователя 5598142592: Member list is inaccessible
2024-09-22 02:02:01,730 [INFO] Инициализация базы данных начата.
2024-09-22 02:02:01,733 [INFO] Таблица users создается
2024-09-22 02:02:01,733 [INFO] Таблица users успешно создана или уже существует.
2024-09-22 02:02:01,733 [INFO] Таблица cars создается
2024-09-22 02:02:01,734 [INFO] Таблица cars успешно создана или уже существует.
2024-09-22 02:02:01,734 [INFO] Таблица purchases создается
2024-09-22 02:02:01,735 [INFO] Таблица purchases успешно создана или уже существует.
2024-09-22 02:02:01,735 [INFO] Таблица earnings создается
2024-09-22 02:02:01,735 [INFO] Таблица earnings успешно создана или уже существует.
2024-09-22 02:02:01,736 [INFO] Таблица channels создается
2024-09-22 02:02:01,736 [INFO] Таблица channels успешно создана или уже существует.
2024-09-22 02:02:01,736 [INFO] Добавление данных в таблицу channels
2024-09-22 02:02:01,737 [INFO] Данные в таблицу channels успешно добавлены.
2024-09-22 02:02:01,737 [INFO] Таблица promo_codes создается
2024-09-22 02:02:01,737 [INFO] Таблица promo_codes успешно создана или уже существует.
2024-09-22 02:02:01,741 [INFO] Инициализация базы данных завершена.
2024-09-22 02:02:01,744 [INFO] Таблицы в базе данных: [('users',), ('cars',), ('purchases',), ('earnings',), ('sqlite_sequence',), ('channels',), ('promo_codes',)]
2024-09-22 02:02:01,747 [INFO] Вставка заранее подготовленных промокодов в базу данных
2024-09-22 02:02:01,749 [INFO] Добавляем промокод: CODE1, категория: normal, награда: 10
2024-09-22 02:02:01,749 [INFO] Добавляем промокод: CODE2, категория: normal, награда: 10
2024-09-22 02:02:01,749 [INFO] Добавляем промокод: CODE3, категория: normal, награда: 10
2024-09-22 02:02:01,750 [INFO] Добавляем промокод: CODE4, категория: normal, награда: 30
2024-09-22 02:02:01,750 [INFO] Добавляем промокод: CODE5, категория: normal, награда: 30
2024-09-22 02:02:01,751 [INFO] Добавляем промокод: CODE6, категория: normal, награда: 50
2024-09-22 02:02:01,751 [INFO] Добавляем промокод: SPECIAL1, категория: special, награда: 100
2024-09-22 02:02:01,751 [INFO] Добавляем промокод: SPECIAL2, категория: special, награда: 150
2024-09-22 02:02:01,752 [INFO] Добавляем промокод: SPECIAL3, категория: special, награда: 200
2024-09-22 02:02:01,752 [INFO] Добавляем промокод: ADVANCED1, категория: advanced, награда: 350
2024-09-22 02:02:01,752 [INFO] Добавляем промокод: ADVANCED2, категория: advanced, награда: 400
2024-09-22 02:02:01,752 [INFO] Добавляем промокод: ADVANCED3, категория: advanced, награда: 450
2024-09-22 02:02:01,754 [INFO] Промокоды успешно вставлены в базу данных
2024-09-22 02:02:01,756 [INFO] Бот успешно запущен.
2024-09-22 02:02:01,756 [INFO] Start polling.
2024-09-22 02:02:01,926 [ERROR] Cause exception while getting updates.
Traceback (most recent call last):
  File "C:\Users\Malam\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\aiogram\dispatcher\dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\aiogram\bot\bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\aiogram\bot\base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\aiogram\bot\api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\aiogram\bot\api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "C:\Users\Malam\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\aiogram\utils\exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
2024-09-22 02:02:07,114 [ERROR] Cause exception while getting updates.
Traceback (most recent call last):
  File "C:\Users\Malam\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\aiogram\dispatcher\dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\aiogram\bot\bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\aiogram\bot\base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\aiogram\bot\api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\aiogram\bot\api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "C:\Users\Malam\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\aiogram\utils\exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
2024-09-22 02:02:12,237 [ERROR] Cause exception while getting updates.
Traceback (most recent call last):
  File "C:\Users\Malam\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\aiogram\dispatcher\dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\aiogram\bot\bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\aiogram\bot\base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\aiogram\bot\api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\aiogram\bot\api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "C:\Users\Malam\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\aiogram\utils\exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
2024-09-22 02:02:17,291 [ERROR] Cause exception while getting updates.
Traceback (most recent call last):
  File "C:\Users\Malam\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\aiogram\dispatcher\dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\aiogram\bot\bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\aiogram\bot\base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\aiogram\bot\api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\aiogram\bot\api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "C:\Users\Malam\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\aiogram\utils\exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
2024-09-22 02:02:22,335 [ERROR] Cause exception while getting updates.
Traceback (most recent call last):
  File "C:\Users\Malam\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\aiogram\dispatcher\dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\aiogram\bot\bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\aiogram\bot\base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\aiogram\bot\api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\aiogram\bot\api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "C:\Users\Malam\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\aiogram\utils\exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
2024-09-22 02:02:27,395 [ERROR] Cause exception while getting updates.
Traceback (most recent call last):
  File "C:\Users\Malam\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\aiogram\dispatcher\dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\aiogram\bot\bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\aiogram\bot\base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\aiogram\bot\api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\aiogram\bot\api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "C:\Users\Malam\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\aiogram\utils\exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
2024-09-22 02:02:32,526 [ERROR] Cause exception while getting updates.
Traceback (most recent call last):
  File "C:\Users\Malam\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\aiogram\dispatcher\dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\aiogram\bot\bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\aiogram\bot\base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\aiogram\bot\api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\aiogram\bot\api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "C:\Users\Malam\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\aiogram\utils\exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
2024-09-22 02:02:37,579 [ERROR] Cause exception while getting updates.
Traceback (most recent call last):
  File "C:\Users\Malam\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\aiogram\dispatcher\dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\aiogram\bot\bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\aiogram\bot\base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\aiogram\bot\api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\aiogram\bot\api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "C:\Users\Malam\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\aiogram\utils\exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
2024-09-22 02:02:41,267 [WARNING] Polling is stopped.
2024-09-22 02:02:41,301 [INFO] Stop polling...
2024-09-22 02:02:41,302 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001D20B475AD0>
2024-09-22 02:02:41,302 [ERROR] Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x000001D20B470910>, 132306.89)]']
connector: <aiohttp.connector.TCPConnector object at 0x000001D20AC41FD0>
2024-09-22 02:05:32,865 [WARNING] Polling is stopped.
2024-09-22 02:05:32,887 [INFO] Stop polling...
2024-09-22 02:05:32,887 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000020F9C7265D0>
2024-09-22 02:08:08,803 [INFO] Инициализация базы данных начата........................................................................................................................................
2024-09-22 02:08:08,807 [INFO] Таблица users создается
2024-09-22 02:08:08,807 [INFO] Таблица users успешно создана или уже существует.
2024-09-22 02:08:08,808 [INFO] Таблица cars создается
2024-09-22 02:08:08,808 [INFO] Таблица cars успешно создана или уже существует.
2024-09-22 02:08:08,808 [INFO] Таблица purchases создается
2024-09-22 02:08:08,809 [INFO] Таблица purchases успешно создана или уже существует.
2024-09-22 02:08:08,809 [INFO] Таблица earnings создается
2024-09-22 02:08:08,809 [INFO] Таблица earnings успешно создана или уже существует.
2024-09-22 02:08:08,810 [INFO] Таблица channels создается
2024-09-22 02:08:08,810 [INFO] Таблица channels успешно создана или уже существует.
2024-09-22 02:08:08,810 [INFO] Добавление данных в таблицу channels
2024-09-22 02:08:08,811 [INFO] Данные в таблицу channels успешно добавлены.
2024-09-22 02:08:08,811 [INFO] Таблица promo_codes создается
2024-09-22 02:08:08,811 [INFO] Таблица promo_codes успешно создана или уже существует.
2024-09-22 02:08:08,817 [INFO] Инициализация базы данных завершена.
2024-09-22 02:08:08,820 [INFO] Таблицы в базе данных: [('users',), ('cars',), ('purchases',), ('earnings',), ('sqlite_sequence',), ('channels',), ('promo_codes',)]
2024-09-22 02:08:08,822 [INFO] Вставка заранее подготовленных промокодов в базу данных..........................................................................................................
2024-09-22 02:08:08,823 [INFO] Добавляем промокод: CODE1, категория: normal, награда: 10
2024-09-22 02:08:08,823 [INFO] Добавляем промокод: CODE2, категория: normal, награда: 10
2024-09-22 02:08:08,823 [INFO] Добавляем промокод: CODE3, категория: normal, награда: 10
2024-09-22 02:08:08,824 [INFO] Добавляем промокод: CODE4, категория: normal, награда: 30
2024-09-22 02:08:08,824 [INFO] Добавляем промокод: CODE5, категория: normal, награда: 30
2024-09-22 02:08:08,824 [INFO] Добавляем промокод: CODE6, категория: normal, награда: 50
2024-09-22 02:08:08,825 [INFO] Добавляем промокод: SPECIAL1, категория: special, награда: 100
2024-09-22 02:08:08,825 [INFO] Добавляем промокод: SPECIAL2, категория: special, награда: 150
2024-09-22 02:08:08,825 [INFO] Добавляем промокод: SPECIAL3, категория: special, награда: 200
2024-09-22 02:08:08,825 [INFO] Добавляем промокод: ADVANCED1, категория: advanced, награда: 350
2024-09-22 02:08:08,825 [INFO] Добавляем промокод: ADVANCED2, категория: advanced, награда: 400
2024-09-22 02:08:08,826 [INFO] Добавляем промокод: ADVANCED3, категория: advanced, награда: 450
2024-09-22 02:08:08,828 [INFO] Промокоды успешно вставлены в базу данных.................................................................................................................
2024-09-22 02:08:08,829 [INFO] Бот успешно запущен.
2024-09-22 02:08:08,829 [INFO] Start polling.
2024-09-22 02:08:19,961 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001E8BAD75DD0>
2024-09-22 19:30:34,321 [INFO] Инициализация базы данных начата........................................................................................................................................
2024-09-22 19:30:34,330 [INFO] Таблица users создается
2024-09-22 19:30:34,331 [INFO] Таблица users успешно создана или уже существует.
2024-09-22 19:30:34,331 [INFO] Таблица cars создается
2024-09-22 19:30:34,331 [INFO] Таблица cars успешно создана или уже существует.
2024-09-22 19:30:34,332 [INFO] Таблица purchases создается
2024-09-22 19:30:34,332 [INFO] Таблица purchases успешно создана или уже существует.
2024-09-22 19:30:34,332 [INFO] Таблица earnings создается
2024-09-22 19:30:34,333 [INFO] Таблица earnings успешно создана или уже существует.
2024-09-22 19:30:34,333 [INFO] Таблица channels создается
2024-09-22 19:30:34,334 [INFO] Таблица channels успешно создана или уже существует.
2024-09-22 19:30:34,334 [INFO] Добавление данных в таблицу channels
2024-09-22 19:30:34,335 [INFO] Данные в таблицу channels успешно добавлены.
2024-09-22 19:30:34,335 [INFO] Таблица promo_codes создается
2024-09-22 19:30:34,335 [INFO] Таблица promo_codes успешно создана или уже существует.
2024-09-22 19:30:34,340 [INFO] Инициализация базы данных завершена.
2024-09-22 19:30:34,345 [INFO] Таблицы в базе данных: [('users',), ('cars',), ('purchases',), ('earnings',), ('sqlite_sequence',), ('channels',), ('promo_codes',)]
2024-09-22 19:30:34,348 [INFO] Вставка заранее подготовленных промокодов в базу данных..........................................................................................................
2024-09-22 19:30:34,350 [INFO] Добавляем промокод: CODE1, категория: normal, награда: 10
2024-09-22 19:30:34,351 [INFO] Добавляем промокод: CODE2, категория: normal, награда: 10
2024-09-22 19:30:34,351 [INFO] Добавляем промокод: CODE3, категория: normal, награда: 10
2024-09-22 19:30:34,352 [INFO] Добавляем промокод: CODE4, категория: normal, награда: 30
2024-09-22 19:30:34,352 [INFO] Добавляем промокод: CODE5, категория: normal, награда: 30
2024-09-22 19:30:34,353 [INFO] Добавляем промокод: CODE6, категория: normal, награда: 50
2024-09-22 19:30:34,354 [INFO] Добавляем промокод: SPECIAL1, категория: special, награда: 100
2024-09-22 19:30:34,355 [INFO] Добавляем промокод: SPECIAL2, категория: special, награда: 150
2024-09-22 19:30:34,355 [INFO] Добавляем промокод: SPECIAL3, категория: special, награда: 200
2024-09-22 19:30:34,356 [INFO] Добавляем промокод: ADVANCED1, категория: advanced, награда: 350
2024-09-22 19:30:34,357 [INFO] Добавляем промокод: ADVANCED2, категория: advanced, награда: 400
2024-09-22 19:30:34,357 [INFO] Добавляем промокод: ADVANCED3, категория: advanced, награда: 450
2024-09-22 19:30:34,360 [INFO] Промокоды успешно вставлены в базу данных.................................................................................................................
2024-09-22 19:30:34,364 [INFO] Бот успешно запущен.
2024-09-22 19:30:34,365 [INFO] Start polling.
2024-09-22 19:30:34,797 [WARNING] Пользователь с ID 1796354346 не найден.
2024-09-22 19:34:40,483 [WARNING] Пользователь с ID 5971799283 не найден.
2024-09-22 19:37:51,967 [WARNING] Polling is stopped.
2024-09-22 19:37:51,990 [INFO] Stop polling...
2024-09-22 19:37:51,991 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001DE3306C690>
2024-09-23 20:54:08,680 [INFO] Инициализация базы данных начата........................................................................................................................................
2024-09-23 20:54:08,691 [INFO] Таблица users создается
2024-09-23 20:54:08,691 [INFO] Таблица users успешно создана или уже существует.
2024-09-23 20:54:08,691 [INFO] Таблица cars создается
2024-09-23 20:54:08,691 [INFO] Таблица cars успешно создана или уже существует.
2024-09-23 20:54:08,691 [INFO] Таблица purchases создается
2024-09-23 20:54:08,693 [INFO] Таблица purchases успешно создана или уже существует.
2024-09-23 20:54:08,693 [INFO] Таблица earnings создается
2024-09-23 20:54:08,693 [INFO] Таблица earnings успешно создана или уже существует.
2024-09-23 20:54:08,693 [INFO] Таблица channels создается
2024-09-23 20:54:08,693 [INFO] Таблица channels успешно создана или уже существует.
2024-09-23 20:54:08,693 [INFO] Добавление данных в таблицу channels
2024-09-23 20:54:08,693 [INFO] Данные в таблицу channels успешно добавлены.
2024-09-23 20:54:08,693 [INFO] Таблица promo_codes создается
2024-09-23 20:54:08,693 [INFO] Таблица promo_codes успешно создана или уже существует.
2024-09-23 20:54:08,697 [INFO] Инициализация базы данных завершена.
2024-09-23 20:54:08,700 [INFO] Таблицы в базе данных: [('users',), ('cars',), ('purchases',), ('earnings',), ('sqlite_sequence',), ('channels',), ('promo_codes',)]
2024-09-23 20:54:08,701 [INFO] Вставка заранее подготовленных промокодов в базу данных..........................................................................................................
2024-09-23 20:54:08,702 [INFO] Добавляем промокод: CODE1, категория: normal, награда: 10
2024-09-23 20:54:08,703 [INFO] Добавляем промокод: CODE2, категория: normal, награда: 10
2024-09-23 20:54:08,704 [INFO] Добавляем промокод: CODE3, категория: normal, награда: 10
2024-09-23 20:54:08,704 [INFO] Добавляем промокод: CODE4, категория: normal, награда: 30
2024-09-23 20:54:08,704 [INFO] Добавляем промокод: CODE5, категория: normal, награда: 30
2024-09-23 20:54:08,704 [INFO] Добавляем промокод: CODE6, категория: normal, награда: 50
2024-09-23 20:54:08,706 [INFO] Добавляем промокод: SPECIAL1, категория: special, награда: 100
2024-09-23 20:54:08,706 [INFO] Добавляем промокод: SPECIAL2, категория: special, награда: 150
2024-09-23 20:54:08,706 [INFO] Добавляем промокод: SPECIAL3, категория: special, награда: 200
2024-09-23 20:54:08,706 [INFO] Добавляем промокод: ADVANCED1, категория: advanced, награда: 350
2024-09-23 20:54:08,706 [INFO] Добавляем промокод: ADVANCED2, категория: advanced, награда: 400
2024-09-23 20:54:08,706 [INFO] Добавляем промокод: ADVANCED3, категория: advanced, награда: 450
2024-09-23 20:54:08,710 [INFO] Промокоды успешно вставлены в базу данных.................................................................................................................
2024-09-23 20:54:08,712 [INFO] Бот успешно запущен.
2024-09-23 20:54:08,712 [INFO] Start polling.
2024-09-23 20:54:20,186 [WARNING] Пользователь с ID 1592830036 не найден.
2024-09-23 20:56:21,497 [WARNING] Polling is stopped.
2024-09-23 20:56:21,510 [INFO] Stop polling...
2024-09-23 20:56:21,510 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x00000178BACD3490>
2024-09-23 20:56:46,791 [INFO] Инициализация базы данных начата........................................................................................................................................
2024-09-23 20:56:46,796 [INFO] Таблица users создается
2024-09-23 20:56:46,796 [INFO] Таблица users успешно создана или уже существует.
2024-09-23 20:56:46,796 [INFO] Таблица cars создается
2024-09-23 20:56:46,797 [INFO] Таблица cars успешно создана или уже существует.
2024-09-23 20:56:46,797 [INFO] Таблица purchases создается
2024-09-23 20:56:46,797 [INFO] Таблица purchases успешно создана или уже существует.
2024-09-23 20:56:46,798 [INFO] Таблица earnings создается
2024-09-23 20:56:46,798 [INFO] Таблица earnings успешно создана или уже существует.
2024-09-23 20:56:46,798 [INFO] Таблица channels создается
2024-09-23 20:56:46,798 [INFO] Таблица channels успешно создана или уже существует.
2024-09-23 20:56:46,798 [INFO] Добавление данных в таблицу channels
2024-09-23 20:56:46,798 [INFO] Данные в таблицу channels успешно добавлены.
2024-09-23 20:56:46,798 [INFO] Таблица promo_codes создается
2024-09-23 20:56:46,798 [INFO] Таблица promo_codes успешно создана или уже существует.
2024-09-23 20:56:46,804 [INFO] Инициализация базы данных завершена.
2024-09-23 20:56:46,806 [INFO] Таблицы в базе данных: [('users',), ('cars',), ('purchases',), ('earnings',), ('sqlite_sequence',), ('channels',), ('promo_codes',)]
2024-09-23 20:56:46,808 [INFO] Вставка заранее подготовленных промокодов в базу данных..........................................................................................................
2024-09-23 20:56:46,810 [INFO] Добавляем промокод: CODE1, категория: normal, награда: 10
2024-09-23 20:56:46,810 [INFO] Добавляем промокод: CODE2, категория: normal, награда: 10
2024-09-23 20:56:46,810 [INFO] Добавляем промокод: CODE3, категория: normal, награда: 10
2024-09-23 20:56:46,811 [INFO] Добавляем промокод: CODE4, категория: normal, награда: 30
2024-09-23 20:56:46,811 [INFO] Добавляем промокод: CODE5, категория: normal, награда: 30
2024-09-23 20:56:46,811 [INFO] Добавляем промокод: CODE6, категория: normal, награда: 50
2024-09-23 20:56:46,812 [INFO] Добавляем промокод: SPECIAL1, категория: special, награда: 100
2024-09-23 20:56:46,812 [INFO] Добавляем промокод: SPECIAL2, категория: special, награда: 150
2024-09-23 20:56:46,812 [INFO] Добавляем промокод: SPECIAL3, категория: special, награда: 200
2024-09-23 20:56:46,813 [INFO] Добавляем промокод: ADVANCED1, категория: advanced, награда: 350
2024-09-23 20:56:46,813 [INFO] Добавляем промокод: ADVANCED2, категория: advanced, награда: 400
2024-09-23 20:56:46,814 [INFO] Добавляем промокод: ADVANCED3, категория: advanced, награда: 450
2024-09-23 20:56:46,816 [INFO] Промокоды успешно вставлены в базу данных.................................................................................................................
2024-09-23 20:56:46,820 [INFO] Бот успешно запущен.
2024-09-23 20:56:46,821 [INFO] Start polling.
2024-09-23 20:57:52,870 [WARNING] Polling is stopped.
2024-09-23 20:57:52,873 [INFO] Stop polling...
2024-09-23 20:57:52,873 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x00000255F7FBFD50>
2024-09-23 20:58:21,055 [INFO] Инициализация базы данных начата........................................................................................................................................
2024-09-23 20:58:21,057 [INFO] Таблица users создается
2024-09-23 20:58:21,057 [INFO] Таблица users успешно создана или уже существует.
2024-09-23 20:58:21,058 [INFO] Таблица cars создается
2024-09-23 20:58:21,058 [INFO] Таблица cars успешно создана или уже существует.
2024-09-23 20:58:21,058 [INFO] Таблица purchases создается
2024-09-23 20:58:21,060 [INFO] Таблица purchases успешно создана или уже существует.
2024-09-23 20:58:21,060 [INFO] Таблица earnings создается
2024-09-23 20:58:21,061 [INFO] Таблица earnings успешно создана или уже существует.
2024-09-23 20:58:21,061 [INFO] Таблица channels создается
2024-09-23 20:58:21,062 [INFO] Таблица channels успешно создана или уже существует.
2024-09-23 20:58:21,062 [INFO] Добавление данных в таблицу channels
2024-09-23 20:58:21,062 [INFO] Данные в таблицу channels успешно добавлены.
2024-09-23 20:58:21,062 [INFO] Таблица promo_codes создается
2024-09-23 20:58:21,063 [INFO] Таблица promo_codes успешно создана или уже существует.
2024-09-23 20:58:21,068 [INFO] Инициализация базы данных завершена.
2024-09-23 20:58:21,073 [INFO] Таблицы в базе данных: [('users',), ('cars',), ('purchases',), ('earnings',), ('sqlite_sequence',), ('channels',), ('promo_codes',)]
2024-09-23 20:58:21,076 [INFO] Вставка заранее подготовленных промокодов в базу данных..........................................................................................................
2024-09-23 20:58:21,077 [INFO] Добавляем промокод: CODE1, категория: normal, награда: 10
2024-09-23 20:58:21,077 [INFO] Добавляем промокод: CODE2, категория: normal, награда: 10
2024-09-23 20:58:21,077 [INFO] Добавляем промокод: CODE3, категория: normal, награда: 10
2024-09-23 20:58:21,077 [INFO] Добавляем промокод: CODE4, категория: normal, награда: 30
2024-09-23 20:58:21,078 [INFO] Добавляем промокод: CODE5, категория: normal, награда: 30
2024-09-23 20:58:21,078 [INFO] Добавляем промокод: CODE6, категория: normal, награда: 50
2024-09-23 20:58:21,078 [INFO] Добавляем промокод: SPECIAL1, категория: special, награда: 100
2024-09-23 20:58:21,079 [INFO] Добавляем промокод: SPECIAL2, категория: special, награда: 150
2024-09-23 20:58:21,079 [INFO] Добавляем промокод: SPECIAL3, категория: special, награда: 200
2024-09-23 20:58:21,079 [INFO] Добавляем промокод: ADVANCED1, категория: advanced, награда: 350
2024-09-23 20:58:21,080 [INFO] Добавляем промокод: ADVANCED2, категория: advanced, награда: 400
2024-09-23 20:58:21,080 [INFO] Добавляем промокод: ADVANCED3, категория: advanced, награда: 450
2024-09-23 20:58:21,083 [INFO] Промокоды успешно вставлены в базу данных.................................................................................................................
2024-09-23 20:58:21,085 [INFO] Бот успешно запущен.
2024-09-23 20:58:21,085 [INFO] Start polling.
2024-09-23 21:04:35,763 [WARNING] Polling is stopped.
2024-09-23 21:04:35,781 [INFO] Stop polling...
2024-09-23 21:04:35,782 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001CE8D0BF9D0>
2024-09-23 21:04:38,219 [INFO] Инициализация базы данных начата........................................................................................................................................
2024-09-23 21:04:38,222 [INFO] Таблица users создается
2024-09-23 21:04:38,223 [INFO] Таблица users успешно создана или уже существует.
2024-09-23 21:04:38,223 [INFO] Таблица cars создается
2024-09-23 21:04:38,224 [INFO] Таблица cars успешно создана или уже существует.
2024-09-23 21:04:38,224 [INFO] Таблица purchases создается
2024-09-23 21:04:38,225 [INFO] Таблица purchases успешно создана или уже существует.
2024-09-23 21:04:38,226 [INFO] Таблица earnings создается
2024-09-23 21:04:38,226 [INFO] Таблица earnings успешно создана или уже существует.
2024-09-23 21:04:38,227 [INFO] Таблица channels создается
2024-09-23 21:04:38,227 [INFO] Таблица channels успешно создана или уже существует.
2024-09-23 21:04:38,227 [INFO] Добавление данных в таблицу channels
2024-09-23 21:04:38,228 [INFO] Данные в таблицу channels успешно добавлены.
2024-09-23 21:04:38,228 [INFO] Таблица promo_codes создается
2024-09-23 21:04:38,229 [INFO] Таблица promo_codes успешно создана или уже существует.
2024-09-23 21:04:38,236 [INFO] Инициализация базы данных завершена.
2024-09-23 21:04:38,240 [INFO] Таблицы в базе данных: [('users',), ('cars',), ('purchases',), ('earnings',), ('sqlite_sequence',), ('channels',), ('promo_codes',)]
2024-09-23 21:04:38,243 [INFO] Вставка заранее подготовленных промокодов в базу данных..........................................................................................................
2024-09-23 21:04:38,246 [INFO] Добавляем промокод: CODE1, категория: normal, награда: 10
2024-09-23 21:04:38,248 [INFO] Добавляем промокод: CODE2, категория: normal, награда: 10
2024-09-23 21:04:38,248 [INFO] Добавляем промокод: CODE3, категория: normal, награда: 10
2024-09-23 21:04:38,249 [INFO] Добавляем промокод: CODE4, категория: normal, награда: 30
2024-09-23 21:04:38,250 [INFO] Добавляем промокод: CODE5, категория: normal, награда: 30
2024-09-23 21:04:38,251 [INFO] Добавляем промокод: CODE6, категория: normal, награда: 50
2024-09-23 21:04:38,251 [INFO] Добавляем промокод: SPECIAL1, категория: special, награда: 100
2024-09-23 21:04:38,252 [INFO] Добавляем промокод: SPECIAL2, категория: special, награда: 150
2024-09-23 21:04:38,252 [INFO] Добавляем промокод: SPECIAL3, категория: special, награда: 200
2024-09-23 21:04:38,252 [INFO] Добавляем промокод: ADVANCED1, категория: advanced, награда: 350
2024-09-23 21:04:38,253 [INFO] Добавляем промокод: ADVANCED2, категория: advanced, награда: 400
2024-09-23 21:04:38,253 [INFO] Добавляем промокод: ADVANCED3, категория: advanced, награда: 450
2024-09-23 21:04:38,255 [INFO] Промокоды успешно вставлены в базу данных.................................................................................................................
2024-09-23 21:04:38,256 [INFO] Бот успешно запущен.
2024-09-23 21:04:38,256 [INFO] Start polling.
2024-09-23 21:05:17,651 [WARNING] Polling is stopped.
2024-09-23 21:05:17,665 [INFO] Stop polling...
2024-09-23 21:05:17,666 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001FB94D8FD50>
2024-09-23 21:05:20,421 [INFO] Инициализация базы данных начата........................................................................................................................................
2024-09-23 21:05:20,424 [INFO] Таблица users создается
2024-09-23 21:05:20,424 [INFO] Таблица users успешно создана или уже существует.
2024-09-23 21:05:20,424 [INFO] Таблица cars создается
2024-09-23 21:05:20,425 [INFO] Таблица cars успешно создана или уже существует.
2024-09-23 21:05:20,425 [INFO] Таблица purchases создается
2024-09-23 21:05:20,425 [INFO] Таблица purchases успешно создана или уже существует.
2024-09-23 21:05:20,425 [INFO] Таблица earnings создается
2024-09-23 21:05:20,426 [INFO] Таблица earnings успешно создана или уже существует.
2024-09-23 21:05:20,426 [INFO] Таблица channels создается
2024-09-23 21:05:20,426 [INFO] Таблица channels успешно создана или уже существует.
2024-09-23 21:05:20,426 [INFO] Добавление данных в таблицу channels
2024-09-23 21:05:20,427 [INFO] Данные в таблицу channels успешно добавлены.
2024-09-23 21:05:20,427 [INFO] Таблица promo_codes создается
2024-09-23 21:05:20,427 [INFO] Таблица promo_codes успешно создана или уже существует.
2024-09-23 21:05:20,433 [INFO] Инициализация базы данных завершена.
2024-09-23 21:05:20,435 [INFO] Таблицы в базе данных: [('users',), ('cars',), ('purchases',), ('earnings',), ('sqlite_sequence',), ('channels',), ('promo_codes',)]
2024-09-23 21:05:20,438 [INFO] Вставка заранее подготовленных промокодов в базу данных..........................................................................................................
2024-09-23 21:05:20,439 [INFO] Добавляем промокод: CODE1, категория: normal, награда: 10
2024-09-23 21:05:20,440 [INFO] Добавляем промокод: CODE2, категория: normal, награда: 10
2024-09-23 21:05:20,440 [INFO] Добавляем промокод: CODE3, категория: normal, награда: 10
2024-09-23 21:05:20,441 [INFO] Добавляем промокод: CODE4, категория: normal, награда: 30
2024-09-23 21:05:20,441 [INFO] Добавляем промокод: CODE5, категория: normal, награда: 30
2024-09-23 21:05:20,442 [INFO] Добавляем промокод: CODE6, категория: normal, награда: 50
2024-09-23 21:05:20,442 [INFO] Добавляем промокод: SPECIAL1, категория: special, награда: 100
2024-09-23 21:05:20,442 [INFO] Добавляем промокод: SPECIAL2, категория: special, награда: 150
2024-09-23 21:05:20,443 [INFO] Добавляем промокод: SPECIAL3, категория: special, награда: 200
2024-09-23 21:05:20,443 [INFO] Добавляем промокод: ADVANCED1, категория: advanced, награда: 350
2024-09-23 21:05:20,444 [INFO] Добавляем промокод: ADVANCED2, категория: advanced, награда: 400
2024-09-23 21:05:20,444 [INFO] Добавляем промокод: ADVANCED3, категория: advanced, награда: 450
2024-09-23 21:05:20,447 [INFO] Промокоды успешно вставлены в базу данных.................................................................................................................
2024-09-23 21:05:20,450 [INFO] Бот успешно запущен.
2024-09-23 21:05:20,450 [INFO] Start polling.
2024-09-23 21:10:38,563 [WARNING] Polling is stopped.
2024-09-23 21:10:39,262 [INFO] Stop polling...
2024-09-23 21:10:39,263 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000014AE9362310>
2024-09-23 21:10:41,830 [INFO] Инициализация базы данных начата........................................................................................................................................
2024-09-23 21:10:41,833 [INFO] Таблица users создается
2024-09-23 21:10:41,834 [INFO] Таблица users успешно создана или уже существует.
2024-09-23 21:10:41,834 [INFO] Таблица cars создается
2024-09-23 21:10:41,834 [INFO] Таблица cars успешно создана или уже существует.
2024-09-23 21:10:41,835 [INFO] Таблица purchases создается
2024-09-23 21:10:41,835 [INFO] Таблица purchases успешно создана или уже существует.
2024-09-23 21:10:41,835 [INFO] Таблица earnings создается
2024-09-23 21:10:41,836 [INFO] Таблица earnings успешно создана или уже существует.
2024-09-23 21:10:41,836 [INFO] Таблица channels создается
2024-09-23 21:10:41,837 [INFO] Таблица channels успешно создана или уже существует.
2024-09-23 21:10:41,837 [INFO] Добавление данных в таблицу channels
2024-09-23 21:10:41,838 [INFO] Данные в таблицу channels успешно добавлены.
2024-09-23 21:10:41,838 [INFO] Таблица promo_codes создается
2024-09-23 21:10:41,838 [INFO] Таблица promo_codes успешно создана или уже существует.
2024-09-23 21:10:41,844 [INFO] Инициализация базы данных завершена.
2024-09-23 21:10:41,849 [INFO] Таблицы в базе данных: [('users',), ('cars',), ('purchases',), ('earnings',), ('sqlite_sequence',), ('channels',), ('promo_codes',)]
2024-09-23 21:10:41,851 [INFO] Вставка заранее подготовленных промокодов в базу данных..........................................................................................................
2024-09-23 21:10:41,852 [INFO] Добавляем промокод: CODE1, категория: normal, награда: 10
2024-09-23 21:10:41,853 [INFO] Добавляем промокод: CODE2, категория: normal, награда: 10
2024-09-23 21:10:41,853 [INFO] Добавляем промокод: CODE3, категория: normal, награда: 10
2024-09-23 21:10:41,854 [INFO] Добавляем промокод: CODE4, категория: normal, награда: 30
2024-09-23 21:10:41,854 [INFO] Добавляем промокод: CODE5, категория: normal, награда: 30
2024-09-23 21:10:41,854 [INFO] Добавляем промокод: CODE6, категория: normal, награда: 50
2024-09-23 21:10:41,855 [INFO] Добавляем промокод: SPECIAL1, категория: special, награда: 100
2024-09-23 21:10:41,855 [INFO] Добавляем промокод: SPECIAL2, категория: special, награда: 150
2024-09-23 21:10:41,855 [INFO] Добавляем промокод: SPECIAL3, категория: special, награда: 200
2024-09-23 21:10:41,856 [INFO] Добавляем промокод: ADVANCED1, категория: advanced, награда: 350
2024-09-23 21:10:41,856 [INFO] Добавляем промокод: ADVANCED2, категория: advanced, награда: 400
2024-09-23 21:10:41,857 [INFO] Добавляем промокод: ADVANCED3, категория: advanced, награда: 450
2024-09-23 21:10:41,859 [INFO] Промокоды успешно вставлены в базу данных.................................................................................................................
2024-09-23 21:10:41,862 [INFO] Бот успешно запущен.
2024-09-23 21:10:41,863 [INFO] Start polling.
2024-09-23 21:12:23,038 [ERROR] Cause exception while getting updates.
Traceback (most recent call last):
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\bot\bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\bot\base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\bot\api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\bot\api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\utils\exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
2024-09-23 21:12:33,136 [ERROR] Cause exception while getting updates.
Traceback (most recent call last):
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\bot\bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\bot\base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\bot\api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\bot\api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\utils\exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
2024-09-23 21:12:43,217 [ERROR] Cause exception while getting updates.
Traceback (most recent call last):
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\bot\bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\bot\base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\bot\api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\bot\api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\utils\exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
2024-09-23 21:12:53,306 [ERROR] Cause exception while getting updates.
Traceback (most recent call last):
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\bot\bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\bot\base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\bot\api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\bot\api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\utils\exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
2024-09-23 21:13:03,428 [ERROR] Cause exception while getting updates.
Traceback (most recent call last):
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\bot\bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\bot\base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\bot\api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\bot\api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\utils\exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
2024-09-23 21:13:13,512 [ERROR] Cause exception while getting updates.
Traceback (most recent call last):
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\bot\bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\bot\base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\bot\api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\bot\api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\utils\exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
2024-09-23 21:13:23,634 [ERROR] Cause exception while getting updates.
Traceback (most recent call last):
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\bot\bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\bot\base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\bot\api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\bot\api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\utils\exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
2024-09-23 21:13:34,019 [ERROR] Cause exception while getting updates.
Traceback (most recent call last):
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\bot\bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\bot\base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\bot\api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\bot\api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\utils\exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
2024-09-23 21:13:44,167 [ERROR] Cause exception while getting updates.
Traceback (most recent call last):
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\bot\bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\bot\base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\bot\api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\bot\api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\utils\exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
2024-09-23 21:13:54,267 [ERROR] Cause exception while getting updates.
Traceback (most recent call last):
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\bot\bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\bot\base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\bot\api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\bot\api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\utils\exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
2024-09-23 21:14:04,343 [ERROR] Cause exception while getting updates.
Traceback (most recent call last):
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\bot\bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\bot\base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\bot\api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\bot\api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\utils\exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
2024-09-23 21:14:14,435 [ERROR] Cause exception while getting updates.
Traceback (most recent call last):
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\bot\bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\bot\base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\bot\api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\bot\api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\utils\exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
2024-09-23 21:14:24,516 [ERROR] Cause exception while getting updates.
Traceback (most recent call last):
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\bot\bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\bot\base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\bot\api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\bot\api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\utils\exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
2024-09-23 21:14:34,613 [ERROR] Cause exception while getting updates.
Traceback (most recent call last):
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\bot\bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\bot\base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\bot\api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\bot\api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\utils\exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
2024-09-23 21:14:44,685 [ERROR] Cause exception while getting updates.
Traceback (most recent call last):
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\bot\bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\bot\base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\bot\api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\bot\api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\utils\exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
2024-09-23 21:14:54,886 [ERROR] Cause exception while getting updates.
Traceback (most recent call last):
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\bot\bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\bot\base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\bot\api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\bot\api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\utils\exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
2024-09-23 21:15:04,992 [ERROR] Cause exception while getting updates.
Traceback (most recent call last):
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\bot\bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\bot\base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\bot\api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\bot\api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\utils\exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
2024-09-23 21:15:15,165 [ERROR] Cause exception while getting updates.
Traceback (most recent call last):
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\bot\bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\bot\base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\bot\api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\bot\api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\utils\exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
2024-09-23 21:15:41,841 [ERROR] Cause exception while getting updates.
Traceback (most recent call last):
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\bot\api.py", line 139, in make_request
    async with session.post(url, data=req, **kwargs) as response:
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiohttp\client.py", line 1167, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiohttp\client.py", line 586, in _request
    await resp.start(conn)
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiohttp\client_reqrep.py", line 905, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiohttp\streams.py", line 616, in read
    await self._waiter
aiohttp.client_exceptions.ClientOSError: [WinError 121] Превышен таймаут семафора

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\bot\bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\bot\base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\bot\api.py", line 142, in make_request
    raise exceptions.NetworkError(f"aiohttp client throws an error: {e.__class__.__name__}: {e}")
aiogram.utils.exceptions.NetworkError: Aiohttp client throws an error: ClientOSError: [WinError 121] Превышен таймаут семафора
2024-09-23 21:16:03,092 [ERROR] Cause exception while getting updates.
Traceback (most recent call last):
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\bot\bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\bot\base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\bot\api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\bot\api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\utils\exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
2024-09-23 21:16:13,277 [ERROR] Cause exception while getting updates.
Traceback (most recent call last):
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\bot\bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\bot\base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\bot\api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\bot\api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\utils\exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
2024-09-23 21:16:23,419 [ERROR] Cause exception while getting updates.
Traceback (most recent call last):
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\bot\bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\bot\base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\bot\api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\bot\api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\utils\exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
2024-09-23 21:16:33,577 [ERROR] Cause exception while getting updates.
Traceback (most recent call last):
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\bot\bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\bot\base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\bot\api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\bot\api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "C:\Users\Malam\OneDrive\Documents\GitHub\BotPYApp\.venv\Lib\site-packages\aiogram\utils\exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
